version: '3'

services:
  nginx:
    build: .docker/nginx
    container_name: nginx
    restart: unless-stopped
    tty: true
    volumes:
      - ./dist:/var/www/html
      - ./.docker/nginx/config/local.conf:/etc/nginx/conf.d/default.conf
    ports:
      - '80:80'
      - '443:443'
    networks:
      - backend

networks:
  backend:
    driver: bridge
